export default {
  "login": "isinnur",
  "id": 98089962,
  "node_id": "U_kgDOBdi76g",
  "avatar_url": "https://avatars.githubusercontent.com/u/98089962?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/isinnur",
  "html_url": "https://github.com/isinnur",
  "followers_url": "https://api.github.com/users/isinnur/followers",
  "following_url": "https://api.github.com/users/isinnur/following{/other_user}",
  "gists_url": "https://api.github.com/users/isinnur/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/isinnur/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/isinnur/subscriptions",
  "organizations_url": "https://api.github.com/users/isinnur/orgs",
  "repos_url": "https://api.github.com/users/isinnur/repos",
  "events_url": "https://api.github.com/users/isinnur/events{/privacy}",
  "received_events_url": "https://api.github.com/users/isinnur/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Işınnur Günay",
  "company": null,
  "blog": "",
  "location": "Antalya, Turkey",
  "email": null,
  "hireable": null,
  "bio": "Pamukkale University Computer Engineering",
  "twitter_username": null,
  "public_repos": 26,
  "public_gists": 0,
  "followers": 24,
  "following": 33,
  "created_at": "2022-01-20T10:15:58Z",
  "updated_at": "2023-05-03T13:27:31Z"
};
